name: Build extensions

on: push

jobs:
  build:
    permissions:
      contents: write
    name: Build extensions
    runs-on: ubuntu-latest # use 'macos-latest' for safari builds, see https://bepp.pigeonposse.com/guide/gh-action#usage for more details
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build extension with BEPP
        uses: pigeonposse/bepp@v1.1.0
      - name: Sign Chrome Extension crx file
        uses: cardinalby/webext-buildtools-chrome-crx-action@2.0.3   
        with:
          zipFilePath: 'build/open-in-stremio-chrome-1.0.2.zip'
          crxFilePath: 'build/open-in-stremio-chrome-1.0.2.crx'
          privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}
          updateXmlPath: 'build/update.xml'
          updateXmlCodebaseUrl: 'https://server.com/extension.crx'
      # publish a release if a tag has been pushed
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/*.zip
